---
abstract: 'Implementation of the di: URI scheme from draft-hallambaker-digesturi'
author:
  - 'Dorian Taylor, C<< <dorian at cpan.org> >>'
  - 'Dorian Taylor <dorian@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-di
no_index:
  directory:
    - inc
    - t
requires:
  Digest: 0
  MIME::Base64: 0
  URI: 0
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: 0.01
